name: Run Wallabot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-wallabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Restore history files from cache
      - name: Restore history cache
        uses: actions/cache@v3
        with:
          path: |
            offers_history.json
            skipped_items_history.json
          # Use a fixed key that doesn't change with each run
          key: wallabot-history-${{ github.repository }}-${{ github.ref }}
          restore-keys: |
            wallabot-history-${{ github.repository }}-${{ github.ref }}
            wallabot-history-${{ github.repository }}
            wallabot-history-
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Update credentials in config.py
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          sed -i "s/username = '.*'/username = '$EMAIL_USERNAME'/" config.py
          sed -i "s/password = '.*'/password = '$EMAIL_PASSWORD'/" config.py
          sed -i "s/receiver = '.*'/receiver = '$EMAIL_RECEIVER'/" config.py
      
      # Create empty history files if they don't exist
      - name: Ensure history files exist
        run: |
          if [ ! -f offers_history.json ]; then
            echo "Creating new offers_history.json file"
            echo '{"urls": []}' > offers_history.json
          fi
          if [ ! -f skipped_items_history.json ]; then
            echo "Creating new skipped_items_history.json file"
            echo '{"urls": []}' > skipped_items_history.json
          fi
      
      - name: Run Wallabot
        run: python wallabot.py --headless
        
      # Upload logs as artifacts for inspection
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: wallabot-logs
          path: wallabot.log
          retention-days: 7